# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 12, 28, 49, 449556, tzinfo=utc)),
        ),
    ]
