# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180713_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 18, 53, 4, 624985, tzinfo=utc)),
        ),
    ]
