# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180714_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 18, 54, 40, 623877, tzinfo=utc)),
        ),
    ]
